include:
  - docker-common.yml
  - docker-redis.yml
  - docker-phpmyadmin.yml
  # Comment the line below to disable the Moodle intermediate upgrade service (3x moodle instances)
  - docker-upgrade-moodle.yml

services:
  build-0:
    extends:
      file: docker-common.yml
      service: build
    container_name: build-0
    deploy:
      replicas: 1
    environment:
      PHP_IMAGE: php:8.1-fpm
      MOODLE_BRANCH_VERSION: MOODLE_311_STABLE
    build:
      args:
        DOCKER_FROM_IMAGE: ${IMAGE_REPO}${PHP_IMAGE:-php:8.1-fpm}
        MOODLE_BRANCH_VERSION: ${MOODLE_BRANCH_VERSION:-MOODLE_311_STABLE}
    volumes:
      - ./temp/docker/build-1/var/www/html:/var/www/html:delegated

  db-0:
    extends:
      file: docker-common.yml
      service: db
    container_name: db-0
    deploy:
      replicas: 1
    volumes:
      - mysqldata-0:/var/lib/mysql:delegated
      - ./temp/db-backups:/tmp/db-backups:delegated

  php-0:
    extends:
      file: docker-common.yml
      service: php
    container_name: php-0
    deploy:
      replicas: 1
    depends_on:
      db-0:
        condition: service_healthy
    environment:
      PHP_IMAGE: php:8.0-fpm
      DB_HOST: db-0
    build:
      args:
        DOCKER_FROM_IMAGE: ${IMAGE_REPO}${PHP_IMAGE:-php:8.0-fpm}
    volumes:
      - ./temp/docker/build-0/var/www/html:/var/www/html:delegated
      - ./temp/docker/moodledata-0:/var/www/moodledata:delegated
    links:
      - db-0
      - redis-primary

  cron-0:
    extends:
      file: docker-common.yml
      service: cron
    container_name: cron-0
    environment:
      DB_DEPLOYMENT_NAME: db-0
      DB_HOST: db-0
    deploy:
      replicas: 1
    depends_on:
      db-0:
        condition: service_healthy
    build:
      context: .
      dockerfile: CRON.Dockerfile
      args:
        DOCKER_FROM_IMAGE: ${IMAGE_REPO}${CRON_IMAGE:-php:8.0-cli}
        PHP_INI_ENVIRONMENT: ${PHP_INI_ENVIRONMENT:-production}
    volumes:
      - ./temp/docker/build-0/var/www/html:/var/www/html:delegated
      - ./temp/docker/moodledata-0:/var/www/moodledata:delegated
    links:
      - db-0
      - redis

  web-0:
    extends:
      file: docker-common.yml
      service: web
    container_name: web-0
    depends_on:
      php-0:
        condition: service_healthy
    deploy:
      replicas: 1
    ports:
        - "${DOCKER_MOODLE_0_PORT:-8081}:${DOCKER_MOODLE_0_PORT:-8081}"
    volumes:
        - ./config/nginx/default_moodle_31.conf:/etc/nginx/conf.d/default.conf:delegated
        - ./temp/docker/build-0/var/www/html:/var/www/html:delegated
        - ./temp/docker/moodledata-0:/var/www/moodledata:delegated
    links:
      - php-0

volumes:
    mysqldata-0: {}

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/16
