version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:8081"
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./temp/var/www:/var/www:delegated
    db:
        image: mariadb:10.5
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_MYSQL_LOCALHOST_USER: 1
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3307:3306
        healthcheck:
          test: [
            "CMD-SHELL",
            "healthcheck.sh --innodb_initialized --connect"
          ]
          interval: 10s
          timeout: 5s
          retries: 5
    php:
        depends_on:
          db:
            condition: service_healthy
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./temp/var/www:/var/www:delegated
        restart: "unless-stopped"
        healthcheck:
          test: [
            "CMD-SHELL",
            "php-fpm-healthcheck.sh --listen-queue=10 --accepted-conn=5000 || kill 1"
          ]
          interval: 10s
          timeout: 5s
          retries: 5
    cron:
        depends_on:
          db:
            condition: service_healthy
        build:
            context: .
            dockerfile: CRON.Dockerfile
        volumes:
            - ./temp/var/www:/var/www:delegated
    redis:
        image: redis:latest
volumes:
    mysqldata: {}
