version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:8081"
        volumes:
            - ./builds/web/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./app:/app:delegated
    php:
        build:
            context: ./builds/php
        volumes:
            - ./app:/app:delegated
    cron:
        build:
            context: .
            dockerfile: ./builds/cron/Dockerfile
        volumes:
            - ./app:/app:delegated
    mysql:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3307:3306
    redis:
        image: redis:latest
volumes:
    mysqldata: {}
