version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:8081"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./temp/var/www:/var/www:delegated
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./temp/var/www:/var/www:delegated
    cron:
        build:
            context: .
            dockerfile: CRON.Dockerfile
        volumes:
            - ./temp/var/www:/var/www:delegated
    db:
        image: mariadb:10.5
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3307:3306
    redis:
        image: redis:latest
volumes:
    mysqldata: {}
