[global]
daemonize = no
process_control_timeout = 20s

[www]
listen = 9000

pm = ondemand
pm.max_children = 1000
pm.process_idle_timeout = 4s
pm.start_servers = 30
pm.min_spare_servers = 30
pm.max_spare_servers = 70
pm.max_requests = 0
pm.status_path = /status

php_flag[display_errors] = on
php_value[memory_limit] = -1
php_value[max_execution_time] = 6000
php_value[max_input_time] = 600
php_value[post_max_size] = 512M
php_value[upload_max_filesize] = 512M

php_value[session.save_handler] = redis
php_value[session.save_path] = tcp://redis-proxy:6379
