pm = static
pm.max_children = 100
pm.process_idle_timeout = 10s
pm.start_servers = 25
pm.min_spare_servers = 25
pm.max_spare_servers = 50
pm.max_requests = 100
pm.status_path = /status

php_flag[display_errors] = on
php_value[memory_limit] = 256M
php_value[max_execution_time] = 600
php_value[max_input_time] = 60
php_value[post_max_size] = 512M
php_value[upload_max_filesize] = 512M
