[global]
daemonize = no
process_control_timeout = 90s

[www]
listen = 9000
listen.backlog = 65536
security.limit_extensions = .php

pm = ondemand
pm.max_children = 10000
pm.process_idle_timeout = 60s
pm.start_servers = 1000
pm.min_spare_servers = 500
pm.max_spare_servers = 1500
pm.max_requests = 5000
pm.status_path = /status

php_flag[display_errors] = on
php_value[memory_limit] = -1
php_value[max_execution_time] = 60000
php_value[max_input_time] = 600
php_value[post_max_size] = 512M
php_value[upload_max_filesize] = 512M

php_value[session.save_handler] = redis
php_value[session.save_path] = tcp://redis-proxy:6379
