#!/bin/bash
# =============================================================================
# POD HEALTH MONITORING SCRIPT
# =============================================================================
# Purpose: Continuous monitoring of pod health with Galera cluster auto-healing
#          Detects errors in pod logs and restarts problematic pods automatically
#
# Deployment:
#   - Runs as CronJob (check-pod-logs.yml) OR
#   - Runs continuously via pod-health-monitor.yml
#   - Requires service account with pod read/delete permissions
#
# Quick Configuration:
#   USE_LOG_AGGREGATOR=true   - Enable webhook notifications (default)
#   USE_LOG_AGGREGATOR=false  - Disable, stdout only
#
# Related Documentation:
#   - Architecture: ../../docs/galera-monitoring-solution.md
#   - Manual intervention: ../../docs/manual-galera-troubleshooting.md
#   - Deployment guide: ./deploy-health-monitor.sh (inline comments)
#   - Log aggregation: See LOG AGGREGATION CONFIGURATION section below
# =============================================================================

# Ensure the script is running with bash
if [ -z "$BASH_VERSION" ]; then
  echo "This script must be run with bash. Switching to bash."
  exec /bin/bash "$0" "$@"
fi

# Source the utility script
source /scripts/_utils.sh

# Initialize utility file arrays for any containerized operations
initialize_utility_arrays

# Ensure kubeconfig is in a writeable location
export KUBECONFIG=/tmp/kubeconfig

# Set up oc to use the service account token
if [[ -n "$OPENSHIFT_TOKEN" && -n "$OPENSHIFT_SERVER" ]]; then
  oc login --token="$OPENSHIFT_TOKEN" --server="$OPENSHIFT_SERVER" --insecure-skip-tls-verify=true
  oc project "$DEPLOY_NAMESPACE"
fi

# =============================================================================
# LOG AGGREGATION CONFIGURATION
# =============================================================================
# Enables inline log aggregation with real-time webhook notifications
#
# Configuration:
#   USE_LOG_AGGREGATOR=true   (default) - Enable real-time event forwarding
#   USE_LOG_AGGREGATOR=false            - Disable, stdout only
#
# Architecture:
#   - Inline: Zero-latency piping via process substitution (current default)
#   - When to use separate: Multiple CronJobs, external syslog, fault isolation
#
# How Inline Works:
#   1. Process substitution: exec 1> >(bash log-aggregator.sh pipe)
#   2. All stdout → log-aggregator.sh in real-time
#   3. Parses CRITICAL_EVENT| structured logs
#   4. Forwards to webhooks (RocketChat/Slack) with zero latency
#   5. Passes through to stdout (visible in pod logs)
#
# Event Format:
#   CRITICAL_EVENT|timestamp|namespace|event_type|message
#   Generated by utility functions in _utils.sh (send_notification)
#
# Related Documentation:
#   - Log aggregator script: ./log-aggregator.sh (inline comments)
#   - Webhook configuration: ./deploy-health-monitor.sh
# =============================================================================
USE_LOG_AGGREGATOR=${USE_LOG_AGGREGATOR:-"true"}

# Function to run with or without log aggregation
run_with_logging() {
  if [[ "$USE_LOG_AGGREGATOR" == "true" && -f "/scripts/log-aggregator.sh" ]]; then
    echo "🔍 Starting pod health checks with inline log aggregation..."
    echo "   Events will be forwarded to configured webhooks in real-time"
    # Use process substitution for zero-latency event processing
    exec 1> >(bash /scripts/log-aggregator.sh pipe)
    exec 2>&1
  else
    echo "🔍 Starting pod health checks (log aggregation disabled)..."
  fi

  echo "Checking pod logs for errors..."
}

# Deployments eligible for error-based restart
# mariadb-galera: handled by dedicated Galera health check above
declare -A RESTART_DEPLOYMENTS
RESTART_DEPLOYMENTS=(
  ["deployment=php"]="error,critical"
  ["app=redis-proxy"]="err:"
)

# Deployments to observe only (log errors, no restart)
# - cron: transient DB/Redis errors during startup, auto-recovers
# - redis-node: restart can cascade-disconnect redis-proxy
# - web: nginx auto-recovers, restart won't help
declare -A OBSERVE_DEPLOYMENTS
OBSERVE_DEPLOYMENTS=(
  ["app=cron"]="error,critical"
  ["app.kubernetes.io/name=redis"]="CRITICAL,lost"
  ["deployment=web"]="emerg,crit"
)

# Initialize logging
run_with_logging

# =============================================================================
# GALERA CLUSTER HEALTH MONITORING AND AUTO-HEALING
# =============================================================================
echo "🩺 Checking Galera cluster health..."
current_namespace=$(oc project -q)

# Check if MariaDB Galera deployment exists
if oc get statefulset mariadb-galera -n "$current_namespace" &> /dev/null; then
  galera_selector="app.kubernetes.io/name=mariadb-galera"
  expected_size=$(oc get statefulset mariadb-galera -n "$current_namespace" -o jsonpath='{.spec.replicas}')

  echo "🔍 Found Galera cluster with expected size: $expected_size pods"

  # Use the existing health check function
  health_status=0
  if check_galera_cluster_health "$galera_selector" "$current_namespace" "$expected_size"; then
    health_status=$?
  else
    health_status=$?
  fi

  case $health_status in
    0)
      echo "✅ Galera cluster is healthy - all pods synchronized"
      ;;
    1)
      echo "⚠️  Galera cluster has unhealthy pods - attempting auto-heal"
      if auto_heal_galera_cluster "$galera_selector" "$current_namespace"; then
        echo "✅ Galera auto-heal completed successfully"
      else
        echo "❌ Galera auto-heal failed - manual intervention may be required"
        # Send critical notification
        send_notification "GALERA_AUTO_HEAL_FAILED" "Galera Auto-Heal Failed" \
          "Auto-healing failed for Galera cluster in $current_namespace. Manual intervention required." \
          "error" "$current_namespace"
      fi
      ;;
    2)
      echo "🚨 CRITICAL: Galera split-brain detected - attempting emergency auto-heal"
      if auto_heal_galera_cluster "$galera_selector" "$current_namespace"; then
        echo "✅ Emergency Galera split-brain recovery completed"
        # Send healing success notification
        send_notification "GALERA_SPLIT_BRAIN_RECOVERED" "Galera Split-Brain Recovered" \
          "Successfully recovered from Galera split-brain condition in $current_namespace" \
          "healing" "$current_namespace"
      else
        echo "❌ CRITICAL: Failed to recover from Galera split-brain - IMMEDIATE ACTION REQUIRED"
        # Send critical notification
        send_notification "GALERA_SPLIT_BRAIN_CRITICAL" "CRITICAL: Galera Split-Brain Recovery Failed" \
          "Failed to recover from split-brain in $current_namespace. Database cluster may be corrupted. IMMEDIATE ACTION REQUIRED." \
          "error" "$current_namespace"
      fi
      ;;
    *)
      echo "❌ Unknown Galera health check status: $health_status"
      ;;
  esac
else
  echo "ℹ️  No MariaDB Galera StatefulSet found in namespace $current_namespace"
fi

# =============================================================================
# POD LOG CHECKING AND ERROR DETECTION
# =============================================================================
echo ""
echo "🔍 Checking pod logs for errors..."

# Main execution
total_checked=0
total_restarted=0

for selector in "${!RESTART_DEPLOYMENTS[@]}"; do
  error_patterns="${RESTART_DEPLOYMENTS[$selector]}"

  echo ""
  echo "════════════════════════════════════════"

  pods_before=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' | wc -w)

  check_and_restart_pod "$selector" "$error_patterns"

  pods_after=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' | wc -w)
  restarted=$((pods_before - pods_after))

  total_checked=$((total_checked + pods_before))
  total_restarted=$((total_restarted + restarted))
done

# Observe-only checks (log errors but never restart)
for selector in "${!OBSERVE_DEPLOYMENTS[@]}"; do
  error_patterns="${OBSERVE_DEPLOYMENTS[$selector]}"

  echo ""
  echo "════════════════════════════════════════"
  echo "🔍 Observing $selector (no restart)"

  pods=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}')
  if [[ -n "$pods" ]]; then
    IFS=',' read -ra patterns <<< "$error_patterns"
    for pod in $pods; do
      logs=$(oc logs "$pod" --tail=50 2>/dev/null)
      for pattern in "${patterns[@]}"; do
        pattern=$(echo "$pattern" | xargs)
        if [[ -n "$pattern" ]] && echo "$logs" | grep -q "$pattern"; then
          echo "  ⚠️  $pod: error pattern '$pattern' detected (observe only)"
          break
        fi
      done
      total_checked=$((total_checked + 1))
    done
  fi
done

echo ""
echo "════════════════════════════════════════"
echo "📊 SUMMARY:"
echo "   Pods checked: $total_checked"
echo "   Pods restarted: $total_restarted"
echo "   Completed at: $(date)"

if [[ $total_restarted -gt 0 ]]; then
  echo "⚠️  $total_restarted pod(s) were restarted due to errors"
  exit 1
else
  echo "✅ All pods are healthy"
  exit 0
fi
