#!/bin/bash
# =============================================================================
# POD HEALTH MONITORING SCRIPT
# =============================================================================
# Purpose: Continuous monitoring of pod health with Galera cluster auto-healing
#          Detects errors in pod logs and restarts problematic pods automatically
#
# Deployment:
#   - Runs as CronJob (check-pod-logs.yml) OR
#   - Runs continuously via pod-health-monitor.yml
#   - Requires service account with pod read/delete permissions
#
# Quick Configuration:
#   USE_LOG_AGGREGATOR=true                  - Enable webhook notifications (default)
#   USE_LOG_AGGREGATOR=false                 - Disable, stdout only
#   ENABLE_MAINTENANCE_MODE_ON_DB_DOWN=true  - Auto-enable maintenance mode when DB offline (default)
#   SKIP_CHECKS_ON_DB_DOWN=true              - Skip Redis/web checks when DB down (default)
#
# Related Documentation:
#   - Architecture: ../../docs/galera-monitoring-solution.md
#   - Manual intervention: ../../docs/manual-galera-troubleshooting.md
#   - Deployment guide: ./deploy-health-monitor.sh (inline comments)
#   - Log aggregation: See LOG AGGREGATION CONFIGURATION section below
# =============================================================================

# Ensure the script is running with bash
if [ -z "$BASH_VERSION" ]; then
  echo "This script must be run with bash. Switching to bash."
  exec /bin/bash "$0" "$@"
fi

# Universal _utils.sh loader - works in all environments
# Priority: same-dir > /scripts > /usr/local/bin > ./openshift/scripts
for _util_path in \
  "$(dirname "${BASH_SOURCE[0]}")/_utils.sh" \
  "/scripts/_utils.sh" \
  "/usr/local/bin/_utils.sh" \
  "./openshift/scripts/_utils.sh"; do
  [[ -f "$_util_path" ]] && source "$_util_path" && break
done
[[ "$(type -t log_info)" != "function" ]] && echo "FATAL: Cannot locate _utils.sh" && exit 1

# Initialize utility file arrays for any containerized operations
initialize_utility_arrays

# Ensure kubeconfig is in a writeable location
export KUBECONFIG=/tmp/kubeconfig

# Check if running in-cluster with service account
if [[ -f "/var/run/secrets/kubernetes.io/serviceaccount/token" && -z "$OPENSHIFT_TOKEN" ]]; then
  log_debug "Running in-cluster with service account - configuring oc to use pod SA token"
  SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
  CLUSTER_SERVER="${OPENSHIFT_SERVER:-https://kubernetes.default.svc}"

  oc login --token="$SA_TOKEN" --server="$CLUSTER_SERVER" --insecure-skip-tls-verify=true
  oc project "$DEPLOY_NAMESPACE"
elif [[ -n "$OPENSHIFT_TOKEN" && -n "$OPENSHIFT_SERVER" ]]; then
  log_debug "Using provided OPENSHIFT_TOKEN for authentication"
  oc login --token="$OPENSHIFT_TOKEN" --server="$OPENSHIFT_SERVER" --insecure-skip-tls-verify=true
  oc project "$DEPLOY_NAMESPACE"
fi

# =============================================================================
# LOG AGGREGATION CONFIGURATION
# =============================================================================
# Enables inline log aggregation with real-time webhook notifications
#
# Configuration:
#   USE_LOG_AGGREGATOR=true   (default) - Enable real-time event forwarding
#   USE_LOG_AGGREGATOR=false            - Disable, stdout only
#
# Architecture:
#   - Inline: Zero-latency piping via process substitution (current default)
#   - When to use separate: Multiple CronJobs, external syslog, fault isolation
#
# How Inline Works:
#   1. Process substitution: exec 1> >(bash log-aggregator.sh pipe)
#   2. All stdout → log-aggregator.sh in real-time
#   3. Parses CRITICAL_EVENT| structured logs
#   4. Forwards to webhooks (RocketChat/Slack) with zero latency
#   5. Passes through to stdout (visible in pod logs)
#
# Event Format:
#   CRITICAL_EVENT|timestamp|namespace|event_type|message
#   Generated by utility functions in _utils.sh (send_notification)
#
# Related Documentation:
#   - Log aggregator script: ./log-aggregator.sh (inline comments)
#   - Webhook configuration: ./deploy-health-monitor.sh
# =============================================================================
USE_LOG_AGGREGATOR=${USE_LOG_AGGREGATOR:-"true"}

# Function to run with or without log aggregation
run_with_logging() {
  if [[ "$USE_LOG_AGGREGATOR" == "true" && -f "/scripts/log-aggregator.sh" ]]; then
    echo "🔍 Starting pod health checks with inline log aggregation..."
    echo "   Events will be forwarded to configured webhooks in real-time"
    # Use process substitution for zero-latency event processing
    exec 1> >(bash /scripts/log-aggregator.sh pipe)
    exec 2>&1
  else
    echo "🔍 Starting pod health checks (log aggregation disabled)..."
  fi

  echo "Checking pod logs for errors..."
}

# Deployments eligible for error-based restart
# mariadb-galera: handled by dedicated Galera health check above
declare -A RESTART_DEPLOYMENTS
RESTART_DEPLOYMENTS=(
  ["deployment=php"]="error,critical"
  ["app=redis-proxy"]="err:"
)

# Deployments to observe only (log errors, no restart)
# - cron: transient DB/Redis errors during startup, auto-recovers
# - redis-node: restart can cascade-disconnect redis-proxy
# - web: nginx auto-recovers, restart won't help
# - mariadb-galera: handled by dedicated health check, observe for WSREP errors
declare -A OBSERVE_DEPLOYMENTS
OBSERVE_DEPLOYMENTS=(
  ["app=cron"]="error,critical"
  ["app.kubernetes.io/name=redis"]="CRITICAL,lost"
  ["deployment=web"]="emerg,crit"
  ["app.kubernetes.io/name=mariadb-galera"]="WSREP.*Unrecognized,WSREP.*Failed,non-Primary,split"
)

# Initialize logging
run_with_logging

# =============================================================================
# CONFIGURATION - Maintenance Mode Integration
# =============================================================================
# Enable maintenance mode when database is offline or during repairs
# Set to "false" to disable automatic maintenance mode activation
ENABLE_MAINTENANCE_MODE_ON_DB_DOWN=${ENABLE_MAINTENANCE_MODE_ON_DB_DOWN:-"true"}

# Skip dependent service checks when database is offline
# (e.g., Redis "lost" errors are expected when DB is down)
SKIP_CHECKS_ON_DB_DOWN=${SKIP_CHECKS_ON_DB_DOWN:-"true"}

# Flag to track database availability for dependent checks
GALERA_OFFLINE=false

# =============================================================================
# GALERA CLUSTER HEALTH MONITORING AND AUTO-HEALING
# =============================================================================
echo "🩺 Checking Galera cluster health..."
current_namespace=$(oc project -q)

# Check if MariaDB Galera deployment exists
if oc get statefulset mariadb-galera -n "$current_namespace" &> /dev/null; then
  galera_selector="app.kubernetes.io/name=mariadb-galera"
  expected_size=$(oc get statefulset mariadb-galera -n "$current_namespace" -o jsonpath='{.spec.replicas}')

  echo "🔍 Found Galera cluster with expected size: $expected_size pods"

  # === CRITICAL: CHECK FOR ZERO REPLICAS (SITE DOWN) ===
  if [[ "$expected_size" -eq 0 ]]; then
    log_critical "🚨 CRITICAL: MariaDB Galera scaled to 0 replicas - SITE IS DOWN"
    log_warn "   Desired state: 0 replicas (intentional or misconfiguration)"
    log_warn "   Impact: Database unavailable, site cannot function"

    send_notification "GALERA_ZERO_REPLICAS" "🚨 CRITICAL: Database Offline" \
      "MariaDB Galera has 0 replicas in $current_namespace. Site is unavailable. This may be intentional (maintenance) or a scaling error." \
      "error" "$current_namespace"

    # Enable maintenance mode if configured
    if [[ "$ENABLE_MAINTENANCE_MODE_ON_DB_DOWN" == "true" ]]; then
      log_info "Enabling maintenance mode (database offline)..."
      if enable_maintenance_mode "maintenance-message" "auto"; then
        log_success "✅ Maintenance mode enabled - users see maintenance page"
      else
        log_error "Failed to enable maintenance mode - users may see error pages"
      fi
    fi

    # Set flag to skip dependent checks
    GALERA_OFFLINE=true

    # Skip all other checks for this cluster
    echo "⏭️  Skipping health checks (0 replicas = intentional offline state)"
  else
    # === NORMAL OPERATION: REPLICAS > 0 ===

    # === WSREP CONFIGURATION CHECK ===
    echo "⚙️  Checking WSREP timeout configuration..."
    running_pods=$(oc get pods -l "$galera_selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' 2>/dev/null)

  if [[ -n "$running_pods" ]]; then
    first_pod=$(echo "$running_pods" | awk '{print $1}')

    # Query actual timeout configuration
    wsrep_timeout=$(oc exec "$first_pod" -n "$current_namespace" -c mariadb-galera -- bash -c \
      'PASS=$(cat /opt/bitnami/mariadb/secrets/mariadb-password | tr -d "\n\r"); mysql -u $(printenv MARIADB_USER) --password="$PASS" -sN -e "SHOW VARIABLES LIKE '\''wsrep_provider_options'\'';" 2>/dev/null | grep -oP "evs\.inactive_timeout\s*=\s*\K[^;]+"' 2>/dev/null || echo "UNKNOWN")

    if [[ "$wsrep_timeout" == "PT15S" ]]; then
      log_warn "⚠️  WSREP Configuration Issue: Using default PT15S timeout"
      log_warn "   This is TOO AGGRESSIVE for OpenShift and may cause split-brain"
      log_warn "   Recommended: PT30S for production, PT20S for dev/test"
      send_notification "WSREP_TIMEOUT_WARNING" "Galera Using Aggressive Timeout" \
        "evs.inactive_timeout=PT15S (default) detected in $current_namespace. Recommended: PT30S. Risk: False-positive split-brain events." \
        "warning" "$current_namespace"
    elif [[ "$wsrep_timeout" =~ ^PT(20|25|30)S$ ]]; then
      log_success "✅ WSREP timeout: $wsrep_timeout (recommended range)"
    elif [[ "$wsrep_timeout" != "UNKNOWN" ]]; then
      log_info "ℹ️  WSREP timeout: $wsrep_timeout (custom configuration)"
    else
      log_debug "   Could not query WSREP timeout (pod may be starting)"
    fi
  fi

  # === WSREP ERROR PATTERN CHECK ===
  echo "🔍 Checking for WSREP errors in pod logs..."
  wsrep_errors_found=false

  for pod in $running_pods; do
    # Check last 100 lines for WSREP errors
    recent_logs=$(oc logs "$pod" -n "$current_namespace" -c mariadb-galera --tail=100 2>/dev/null || echo "")

    # Critical WSREP errors that indicate configuration or cluster problems
    if echo "$recent_logs" | grep -q "WSREP: Unrecognized parameter"; then
      log_error "❌ $pod: Invalid WSREP parameter detected (configuration error)"
      send_notification "WSREP_CONFIG_ERROR" "Galera Configuration Error" \
        "Pod $pod has invalid WSREP parameters. Check extraFlags or my.cnf configuration." \
        "error" "$current_namespace"
      wsrep_errors_found=true
    fi

    if echo "$recent_logs" | grep -q "WSREP: Failed to create.*provider"; then
      log_error "❌ $pod: WSREP provider failed to initialize"
      wsrep_errors_found=true
    fi

    if echo "$recent_logs" | grep -q "non-Primary"; then
      log_warn "⚠️  $pod: Node in non-Primary state (possible split-brain component)"
      wsrep_errors_found=true
    fi

    if echo "$recent_logs" | grep -q "split.*brain"; then
      log_critical "🚨 $pod: Split-brain mentioned in logs"
      wsrep_errors_found=true
    fi
  done

  if $wsrep_errors_found; then
    log_warn "⚠️  WSREP errors detected - cluster may need attention"
  else
    log_debug "   No WSREP errors found in recent logs"
  fi

  # === READ-ONLY MODE CHECK ===
  # After bootstrap recovery or restore, nodes can end up with read_only=ON
  # which causes "READONLY You can't write against a read only replica" in Moodle.
  # Galera multi-master requires all nodes writable.
  echo "🔒 Checking for read-only nodes..."
  read_only_fixed=0

  for pod in $running_pods; do
    read_only_status=$(oc exec "$pod" -n "$current_namespace" -c mariadb-galera -- bash -c \
      'PASS=$(cat /opt/bitnami/mariadb/secrets/mariadb-password | tr -d "\n\r"); mysql -u $(printenv MARIADB_USER) --password="$PASS" -sN -e "SELECT @@read_only;" 2>/dev/null' 2>/dev/null || echo "UNKNOWN")

    if [[ "$read_only_status" == "1" ]]; then
      log_warn "⚠️  $pod: read_only=ON — Moodle cannot write to this node"

      if [[ "${MANUAL_MODE,,}" == "true" ]]; then
        log_info "   [MANUAL MODE] Would run SET GLOBAL read_only=OFF on $pod"
      else
        # Fix: disable read_only so the node accepts writes
        oc exec "$pod" -n "$current_namespace" -c mariadb-galera -- bash -c \
          'PASS=$(cat /opt/bitnami/mariadb/secrets/mariadb-root-password | tr -d "\n\r"); mysql -u root --password="$PASS" -e "SET GLOBAL read_only=OFF;" 2>/dev/null' 2>/dev/null

        if [[ $? -eq 0 ]]; then
          log_success "   ✅ Fixed: SET GLOBAL read_only=OFF on $pod"
          read_only_fixed=$((read_only_fixed + 1))
        else
          log_error "   ❌ Failed to disable read_only on $pod (may need manual fix)"
        fi
      fi
    elif [[ "$read_only_status" == "0" ]]; then
      log_debug "   $pod: read_only=OFF (writable)"
    else
      log_debug "   $pod: could not query read_only status"
    fi
  done

  if [[ $read_only_fixed -gt 0 ]]; then
    send_notification "GALERA_READONLY_FIXED" "Galera Read-Only Nodes Fixed" \
      "Disabled read_only on $read_only_fixed node(s) in $current_namespace. Nodes were likely left in read-only state after bootstrap recovery or restore." \
      "healing" "$current_namespace"
  fi

  # === STALE BOOTSTRAP ENV VAR CHECK ===
  # Bootstrap env vars must not persist after recovery — they cause galera-0 to
  # bootstrap a standalone cluster on every restart instead of rejoining.
  echo "🔧 Checking for stale bootstrap environment variables..."
  bootstrap_val=$(oc get statefulset mariadb-galera -n "$current_namespace" \
    -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name=="MARIADB_GALERA_CLUSTER_BOOTSTRAP")].value}' 2>/dev/null || echo "")

  if [[ "$bootstrap_val" == "yes" ]]; then
    log_warn "⚠️  MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes is still set on StatefulSet!"
    log_warn "   This causes galera-0 to bootstrap standalone on every restart."

    if [[ "${MANUAL_MODE,,}" == "true" ]]; then
      log_info "   [MANUAL MODE] Would remove bootstrap env vars from StatefulSet"
    else
      log_info "   [ACTION] Removing stale bootstrap env vars..."
      oc set env statefulset/mariadb-galera -n "$current_namespace" \
        MARIADB_GALERA_CLUSTER_BOOTSTRAP- \
        MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP- \
        MARIADB_GALERA_CLUSTER_ADDRESS- 2>/dev/null

      if [[ $? -eq 0 ]]; then
        log_success "   ✅ Removed stale bootstrap env vars from StatefulSet"
        send_notification "GALERA_BOOTSTRAP_VARS_CLEANED" "Stale Bootstrap Env Vars Removed" \
          "Removed MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes and related vars from StatefulSet in $current_namespace. These were left over from a previous recovery." \
          "healing" "$current_namespace"
      else
        log_error "   ❌ Failed to remove bootstrap env vars"
      fi
    fi
  else
    log_debug "   No stale bootstrap env vars detected"
  fi

  # === CLUSTER HEALTH CHECK ===
  # Use the existing health check function
  health_status=0
  if check_galera_cluster_health "$galera_selector" "$current_namespace" "$expected_size"; then
    health_status=$?
  else
    health_status=$?
  fi

  case $health_status in
    0)
      echo "✅ Galera cluster is healthy - all pods synchronized"
      ;;
    1)
      echo "⚠️  Galera cluster has unhealthy pods - attempting auto-heal"

      # Enable maintenance mode before healing if configured
      if [[ "$ENABLE_MAINTENANCE_MODE_ON_DB_DOWN" == "true" ]]; then
        log_info "Enabling maintenance mode before auto-heal..."
        enable_maintenance_mode "maintenance-message" "auto"
      fi

      if auto_heal_galera_cluster "$galera_selector" "$current_namespace"; then
        echo "✅ Galera auto-heal completed successfully"

        # Disable maintenance mode after successful heal
        if [[ "$ENABLE_MAINTENANCE_MODE_ON_DB_DOWN" == "true" ]]; then
          log_info "Disabling maintenance mode (cluster healthy)..."
          if disable_maintenance_mode "web" "maintenance-message" "auto"; then
            log_success "✅ Maintenance mode disabled - site restored"
          fi
        fi
      else
        echo "❌ Galera auto-heal failed - manual intervention may be required"
        # Send critical notification
        send_notification "GALERA_AUTO_HEAL_FAILED" "Galera Auto-Heal Failed" \
          "Auto-healing failed for Galera cluster in $current_namespace. Manual intervention required." \
          "error" "$current_namespace"
        # NOTE: Maintenance mode stays enabled until manual fix
      fi
      ;;
    2)
      echo "🚨 CRITICAL: Galera split-brain detected - attempting emergency auto-heal"

      # Enable maintenance mode before emergency repair
      if [[ "$ENABLE_MAINTENANCE_MODE_ON_DB_DOWN" == "true" ]]; then
        log_info "Enabling maintenance mode before split-brain repair..."
        enable_maintenance_mode "maintenance-message" "auto"
      fi

      if auto_heal_galera_cluster "$galera_selector" "$current_namespace"; then
        echo "✅ Emergency Galera split-brain recovery completed"
        # Send healing success notification
        send_notification "GALERA_SPLIT_BRAIN_RECOVERED" "Galera Split-Brain Recovered" \
          "Successfully recovered from Galera split-brain condition in $current_namespace" \
          "healing" "$current_namespace"

        # Disable maintenance mode after successful recovery
        if [[ "$ENABLE_MAINTENANCE_MODE_ON_DB_DOWN" == "true" ]]; then
          log_info "Disabling maintenance mode (split-brain resolved)..."
          if disable_maintenance_mode "web" "maintenance-message" "auto"; then
            log_success "✅ Maintenance mode disabled - site restored"
          fi
        fi
      else
        echo "❌ CRITICAL: Failed to recover from Galera split-brain - IMMEDIATE ACTION REQUIRED"
        # Send critical notification
        send_notification "GALERA_SPLIT_BRAIN_CRITICAL" "CRITICAL: Galera Split-Brain Recovery Failed" \
          "Failed to recover from split-brain in $current_namespace. Database cluster may be corrupted. IMMEDIATE ACTION REQUIRED." \
          "error" "$current_namespace"
        # NOTE: Maintenance mode stays enabled until manual fix
      fi
      ;;
    *)
      echo "❌ Unknown Galera health check status: $health_status"
      ;;
  esac
  fi  # End of else block (expected_size > 0)
else
  echo "ℹ️  No MariaDB Galera StatefulSet found in namespace $current_namespace"
fi

# =============================================================================
# POD LOG CHECKING AND ERROR DETECTION
# =============================================================================
echo ""
echo "🔍 Checking pod logs for errors..."

# Main execution
total_checked=0
total_restarted=0

for selector in "${!RESTART_DEPLOYMENTS[@]}"; do
  error_patterns="${RESTART_DEPLOYMENTS[$selector]}"

  echo ""
  echo "════════════════════════════════════════"

  pods_before=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' | wc -w)

  check_and_restart_pod "$selector" "$error_patterns"

  pods_after=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' | wc -w)
  restarted=$((pods_before - pods_after))

  total_checked=$((total_checked + pods_before))
  total_restarted=$((total_restarted + restarted))
done

# Observe-only checks (log errors but never restart)
# Skip if database is offline (cascading failures are expected)
if [[ "$SKIP_CHECKS_ON_DB_DOWN" == "true" ]] && [[ "$GALERA_OFFLINE" == "true" ]]; then
  echo ""
  echo "════════════════════════════════════════"
  echo "⏭️  Skipping observe-only checks (database offline)"
  echo "   Reason: Database unavailable - dependent service errors are expected"
  echo "   Affected: Redis, Web, Cron error monitoring"
elif [[ "$GALERA_OFFLINE" == "true" ]]; then
  echo ""
  echo "════════════════════════════════════════"
  echo "⚠️  WARNING: Database offline but SKIP_CHECKS_ON_DB_DOWN=false"
  echo "   Expect false-positive errors from dependent services"
fi

for selector in "${!OBSERVE_DEPLOYMENTS[@]}"; do
  # Skip dependent service checks if database is offline
  if [[ "$SKIP_CHECKS_ON_DB_DOWN" == "true" ]] && [[ "$GALERA_OFFLINE" == "true" ]]; then
    # Skip all non-Galera checks when DB is down
    if [[ "$selector" != "app.kubernetes.io/name=mariadb-galera" ]]; then
      continue
    fi
  fi

  error_patterns="${OBSERVE_DEPLOYMENTS[$selector]}"

  echo ""
  echo "════════════════════════════════════════"
  echo "🔍 Observing $selector (no restart)"

  pods=$(oc get pods -l "$selector" --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}')
  if [[ -n "$pods" ]]; then
    IFS=',' read -ra patterns <<< "$error_patterns"
    for pod in $pods; do
      logs=$(oc logs "$pod" --tail=50 2>/dev/null)
      for pattern in "${patterns[@]}"; do
        pattern=$(echo "$pattern" | xargs)
        if [[ -n "$pattern" ]] && echo "$logs" | grep -q "$pattern"; then
          echo "  ⚠️  $pod: error pattern '$pattern' detected (observe only)"
          break
        fi
      done
      total_checked=$((total_checked + 1))
    done
  fi
done

echo ""
echo "════════════════════════════════════════"
echo "📊 SUMMARY:"
echo "   Pods checked: $total_checked"
echo "   Pods restarted: $total_restarted"
echo "   Completed at: $(date)"

if [[ $total_restarted -gt 0 ]]; then
  echo "⚠️  $total_restarted pod(s) were restarted due to errors"
  exit 1
else
  echo "✅ All pods are healthy"
  exit 0
fi
