apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-logs
  namespace: e66ac2-dev
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-logs
              image: openshift/origin-cli
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
              command: ["/bin/sh", "-c"]
              args:
                - /scripts/check-pod-logs.sh
              env:
                - name: OPENSHIFT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-actions-sa-token-bcgk6
                      key: token
                - name: OPENSHIFT_SERVER
                  value: ${OPENSHIFT_SERVER}
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: check-pod-logs-script