
# Generalised template for building from Dockerfile in a git repo.
# Includes importing the base image as an imagestream.
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${BASE_IMAGE_NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStreamTag
    lookupPolicy:
      local: false
    metadata:
      name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
    tag:
      annotations: null
      from:
        kind: DockerImage
        name: ${BASE_IMAGE_REPO}${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
    spec:
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${TAG}"
      runPolicy: SerialLatestOnly
      source:
        contextDir: "${SOURCE_CONTEXT_DIR}"
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${BASE_IMAGE_TAG}"
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
          buildArgs:
            - name: SITE_URL
              value: ${SITE_URL}
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_NAME
              value: ${DB_NAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: DB_USER
              value: ${DB_USER}
        type: Docker
parameters:
  - name: NAME
    required: true
  - name: SOURCE_CONTEXT_DIR
    value: \
  - name: SOURCE_REPOSITORY_URL
    value: https://github.com/bcgov/moodle.git
  - name: TAG
    value: "latest"
  - name: BASE_IMAGE_REPO
    value: ""
  - name: BASE_IMAGE_NAME
    required: true
    value: "moodle"
  - name: BASE_IMAGE_TAG
    required: true
  - name: CPU_LIMIT
    value: "4"
  - name: MEMORY_LIMIT
    value: "8Gi"
  - name: CPU_REQUEST
    value: "2"
  - name: MEMORY_REQUEST
    value: "8Gi"
  - name: SITE_URL
  - name: DB_HOST
    required: true
  - name: DB_NAME
    required: true
  - name: DB_PASSWORD
    required: true
  - name: DB_USER
    required: true
