
# Generalised template for building from Dockerfile in a git repo.
# Includes importing the base image as an imagestream.
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${BASE_IMAGE_NAME}-${BASE_IMAGE_TAG}
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${BASE_IMAGE_NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStreamTag
    lookupPolicy:
      local: false
    metadata:
      name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
    tag:
      annotations: null
      from:
        kind: DockerImage
        name: ${BASE_IMAGE_REPO}${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${BASE_IMAGE_NAME}-${BASE_IMAGE_TAG}
    spec:
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
      output:
        to:
          kind: ImageStreamTag
          name: "${BASE_IMAGE_NAME}:${TAG}"
      runPolicy: SerialLatestOnly
      source:
        contextDir: "${SOURCE_CONTEXT_DIR}"
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${TAG}"
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: "${DOCKERFILE}"
          buildArgs:
          - name: "DB_HOST"
            value: "${DB_HOST}"
          - name: "DB_NAME"
            value: "moodle"
          - name: "DB_USER"
            value: "moodle"
          - name: "DB_PASSWORD"
            value: "${DB_PASSWORD}"
        type: Docker
parameters:
  - name: SUFFIX
  - name: SOURCE_CONTEXT_DIR
    value: .
  - name: DOCKERFILE
    value: "Dockerfile"
  - name: SOURCE_REPOSITORY_URL
    value: https://github.com/bcgov/moodle-nginx.git
  - name: TAG
    value: "latest"
  - name: BASE_IMAGE_REPO
  - name: BASE_IMAGE_NAME
    required: true
  - name: BASE_IMAGE_TAG
    value: "prod"
  - name: CPU_LIMIT
    value: "1"
  - name: CPU_REQUEST
    value: "0.25"
  - name: MEMORY_LIMIT
    value: "2Gi"
  - name: MEMORY_REQUEST
    value: "128Mi"
  - name: DB_HOST
    value: "mariadb-sts-0.mariadb"
  - name: DB_PASSWORD
    value: "128Mi"