# ConfigMap holding information about configuration files for primary/secondary and dockerinit
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)
    max_allowed_packet=1073741824

  replica.cnf: |
    [mariadb]
    log-basename=mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)
    max_allowed_packet=1073741824
    slave-skip-errors=1396

  primary.sql: |
    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser'@'%';
    CREATE DATABASE moodle;

  secondary.sql: |
    # We have to know name of sts (`mariadb-sts`) and
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port
    CHANGE MASTER TO
    MASTER_HOST='mariadb-sts-0.mariadb-service.default.svc.cluster.local',
    MASTER_USER='repluser',
    MASTER_PASSWORD='replsecret',
    MASTER_CONNECT_RETRY=10;