apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: migrate-build-files
objects:
 - apiVersion: batch/v1
   kind: Job
   metadata:
     name: migrate-build-files
     namespace: ${BUILD_NAMESPACE}
   spec:
     parallelism: 1
     completions: 1
     backoffLimit: 80
     template:
       metadata:
         name: migrate-build-files
       spec:
         terminationGracePeriodSeconds: 108000
         volumes:
           - name: moodle-data
             persistentVolumeClaim:
               claimName: moodle-data
           - name: moodle-app-data
             persistentVolumeClaim:
               claimName: moodle-app-data
           - name: moodle-env
             configMap:
               name: moodle-env
               items:
                 - key: .env
                   path: ./.env
               defaultMode: 420
         imagePullSecrets:
           - name: artifactory-m950-learning
         containers:
           - name: migrate-build-files-job
             image: ${IMAGE_REPO}${BUILD_NAME}:${BUILD_NAMESPACE}
             volumeMounts:
               - name: moodle-app-data
                 mountPath: /var/www/html
               - name: moodle-data
                 mountPath: /var/www/moodledata
               - name: moodle-env
                 mountPath: .env
                 subPath: .env
             env:
               - name: DB_USER
                 valueFrom:
                   secretKeyRef:
                     name: moodle-secrets
                     key: database-user
               - name: DB_NAME
                 valueFrom:
                   secretKeyRef:
                     name: moodle-secrets
                     key: database-name
               - name: DB_PASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: moodle-secrets
                     key: database-password
             command:
               - bash
               - "-c"
               - |
                echo "Migrating build files from /app/public to /var/www/html..."
                sh /usr/local/bin/migrate-build-files.sh
             imagePullPolicy: Always
         restartPolicy: Never
parameters:
  - name: IMAGE_REPO
    required: true
    value: "artifacts.developer.gov.bc.ca/m950-learning/"
  - name: BUILD_NAMESPACE
    required: true
    value: "e66ac2-dev"
  - name: BUILD_NAME
    required: true
    value: "moodle"
