apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${APP}-${WEB_DEPLOYMENT_NAME}
  namespace: ${DEPLOY_NAMESPACE}
spec:
  to:
    kind: Service
    name: ${WEB_DEPLOYMENT_NAME}
  host: ${SITE_URL}
  port:
    targetPort: 8080
  tls:
    termination: edge
