---
apiVersion: v1
kind: Template
name: ${NAME}-config-template
labels:
  app: ${NAME}
  app.kubernetes.io/component: ${NAME}
  app.kubernetes.io/name: ${NAME}
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/part-of: ${NAME}
  app.kubernetes.io/version: "6"
  template: ${NAME}-secret-template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-config
    data:
      /etc/nginx/conf.d/default.conf: |-
        server {
          listen 8081 default_server;
          root /var/www/html;

          index index.php index.html index.htm;

          location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info  ^(.+\.php)(/.+)$;
            fastcgi_index            index.php;
            fastcgi_pass             php:9000;
            include                  fastcgi_params;
            fastcgi_read_timeout     1200s;
            fastcgi_param   PATH_INFO       $fastcgi_path_info;
            fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
          }
        }
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: moodle-web
  - name: REACT_APP_SL_REVIEW_PROCESS_NAME
    displayName: REACT_APP_SL_REVIEW_PROCESS_NAME
    description: SL Review process name
    required: true