global:
  redis:
    password: ""
redis:
  persistence:
    enabled: false
    size: 600Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
updateJob:
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
replica:
  replicaCount: 5
  persistence:
    enabled: false
    size: 0Mi
  autoscaling:
    enabled: false
    minReplicas: 5
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      memory: 32Mi
      cpu: 100m
sentinel:
  enabled: true
  usePassword: false
  externalAccess:
    enabled: false
  automateClusterRecovery: true
  persistence:
    enabled: false
    size: 0Mi
  resources:
    requests:
      memory: 32Mi
      cpu: 5m
auth:
  enabled: false
  sentinel: false
  password: ""
  usePassword: false
  usePasswordFileFromSecret: false
image:
  pullPolicy: Always
  debug: false
