global:
  redis:
    password: ""
redis:
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      cpu: 80m
updateJob:
  resources:
    requests:
      memory: 32Mi
      cpu: 5m
    limits:
      cpu: 10m
replica:
  replicaCount: 6
  persistence:
    enabled: true
    size: 200Mi
  autoscaling:
    enabled: true
    minReplicas: 6
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      cpu: 80m
sentinel:
  enabled: true
  automateClusterRecovery: true
  persistence:
    enabled: false
    size: 20Mi
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      cpu: 80m
auth:
  enabled: false
  sentinel: false
  password: ""
  usePasswordFileFromSecret: false
image:
  pullPolicy: Always
  debug: true
