global:
  redis:
    password: ""
replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 100Mi
sentinel:
  enabled: true
  persistence:
    enabled: true
    size: 20Mi
auth:
  enabled: false
  sentinel: false
  password: ""
  usePasswordFileFromSecret: false