redis:
  persistence:
    enabled: false
    size: 600Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
replicas:
  replicaCount: 5
  persistence:
    enabled: false
sentinel:
  enabled: true
  externalAccess:
    enabled: false
  automateClusterRecovery: true
  persistence:
    enabled: false
    size: 0Mi
  resources:
    requests:
      memory: 32Mi
      cpu: 5m
