name: 🔨 Build and publish Moodle image to Artifactory

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# env:
#   APP: moodle
#   DOCKERFILE: Moodle.Dockerfile
#   USER: ${{ github.actor }}
#   OPENSHIFT_DEPLOY_PROJECT: e66ac2
#   BUILD_NAMESPACE: ${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}
#   ARTIFACTORY_URL: artifacts.developer.gov.bc.ca/m950-learning
#   JFROG_PATH: ${{ env.ARTIFACTORY_URL }}/${{ env.APP }}:${{ env.BUILD_NAMESPACE }}






on:
  workflow_dispatch:
    inputs:
      APP:
        description: 'Application to build'
        required: true
        type: choice
        options:
        - moodle
        - pdp
        - pecsf
      OPENSHIFT_DEPLOY_PROJECT:
        description: 'Openshift deploy project'
        required: true
        type: choice
        options:
        - e66ac2
        - 332842
        - 1fd77b
  # push:
  #   branches:
  #   - dev
  #   #- test
  #   #- prod
  #   paths:
  #   - '**.Dockerfile'
  # pull_request:
  #   branches:
  #   - dev
  #   #- test
  #   #- prod
  #   paths:
  #   - 'Moodle.Dockerfile'
  #   - '**/config/moodle/**'
  #   - '**/workflows/artifactory-moodle.yml'


env:
    APP: ${{ inputs.APP}}
    DOCKERFILE: ${{ inputs.APP}}.Dockerfile
    USER: ${{ github.actor }}
    OPENSHIFT_DEPLOY_PROJECT: ${{ inputs.OPENSHIFT_DEPLOY_PROJECT }}
    BUILD_NAMESPACE: ${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}
    ARTIFACTORY_URL: artifacts.developer.gov.bc.ca/m950-learning
    JFROG_PATH: ${{ env.ARTIFACTORY_URL }}/${{ env.APP }}:${{ env.BUILD_NAMESPACE }}
jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: 📋 Environment Check
    runs-on: ubuntu-latest
    steps:
    - name: Check Env Vars
      run: |
        echo Building ${{ env.APP }}:${{ github.ref_name }}

  # Build PHP Image
  build-images:
    name: '🔨 Build Moodle Imag ${{ env.APP }}:${{ github.ref_name }}'
    needs: [checkEnv]
    runs-on: ubuntu-latest
    if: ${{ needs.checkEnv.SKIP_BUILDS != 'YES' }} && (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
    # Checkout the PR branch
    - name: 📤 Checkout Target Branch
      uses: actions/checkout@v2

    # # Login to Artifactory
    # - name: 🔑 Login to Artifactory
    #   run: |
    #     docker login  artifacts.developer.gov.bc.ca/m950-learning -u default-950003-gtjsbf -p TBjwhMFnDkox50RfpUk61A5i
    
    # Build the Docker image
    - name: 🛠️ Build Moodle Image
      run: |
        docker build -t ${{ env.JFROG_PATH }} . -f ${{ env.DOCKERFILE}}

    # Login to Artifactory
    - name: 🔑 Login to Artifactory
      run: |
        docker login ${{ env.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USER }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}

    # Push the Docker image to Artifactory
    # - name: 🚀 Push Docker image to Artifactory
    #   run: |
    #     docker push ${{ env.JFROG_PATH }}
