name: 🔨 Build and publish Moodle image to Artifactory

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  APP: moodle
  USER: ${{ github.actor }}

on:
  push:
    branches:
      - dev
      #- test
      #- prod
    paths:
      - '**.Dockerfile'
  pull_request:
    branches:
      - dev
      #- test
      #- prod
    paths:
      - 'Moodle.Dockerfile'
      - 'PHP.Dockerfile'
      - 'CRON.Dockerfile'
      - '**/config/moodle/**'
      - '**/config/php/**'
      - '**/config/cron/**'
      - '**/workflows/build-moodle-jfrog.yml'
jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: 📋 Environment Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Env Vars
        run: |
          echo Building ${{ env.APP }}:${{ github.ref_name }}

  # Build Images

  build-images:
    name: '🔨 Build Moodle and PHP images'
    needs: [checkEnv]
    runs-on: ubuntu-latest
    if: ${{ needs.checkEnv.SKIP_BUILDS != 'YES' }} && (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
      # Checkout the PR branch
      - name: 📤 Checkout Target Branch
        uses: actions/checkout@v2

      - name: 🛠️ Build Moodle Image
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_URL }}/moodle:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} . -f Moodle.Dockerfile

      - name: 🛠️ Build PHP Image
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_URL }}/php:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} . -f PHP.Dockerfile

      - name: 🛠️ Build CRON Image
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_URL }}/cron:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} . -f CRON.Dockerfile

      # Login to Artifactory
      - name: 🔑 Login to Artifactory
        run: |
          docker login ${{ secrets.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USER }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: 🚀 Push Moodle image to Artifactory
        run: |
          docker push ${{ secrets.ARTIFACTORY_URL }}/moodle:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}

      - name: 🚀 Push PHP image to Artifactory
        run: |
          docker push ${{ secrets.ARTIFACTORY_URL }}/php:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}

      - name: 🚀 Push CRON image to Artifactory
        run: |
          docker push ${{ secrets.ARTIFACTORY_URL }}/cron:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }}
