name: DB

concurrency:
  group: db-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_REBUILD_TIME_LIMIT:
        description: "The maximum allowable time (in seconds) since the last build"
        required: true
        type: number
jobs:
  build-images:
    name: '🐸 Build to JFrog'
    runs-on: ubuntu-22.04
    #env:
      # Proxy settings for local development / testing
      #https_proxy: http://198.161.14.25:8080
      # no_proxy: ${{ env.OPENSHIFT_SERVER }}
    if: (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
      - name: 📤 Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: dev
          sparse-checkout: |
            config/mariadb
            example.env
            example.versions.env

      - name: Setup Env Vars
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: example.env
          export-variables: true
          keys-case: upper

      - name: Setup Env Version Vars
        id: dotenv_versions
        uses: falti/dotenv-action@v1
        with:
          path: example.versions.env
          export-variables: true
          keys-case: upper

      - name: Check Env Vars
        run: |
          echo Building and pushing IMAGE_NAME: ${{ env.IMAGE_NAME }}

      # Login to Artifactory
      - name: 🔑 Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Check Image in Artifactory
        id: check-artifactory
        run: |
          # Define variables
          ARTIFACTORY_URL="${{ secrets.ARTIFACTORY_URL }}"
          IMAGE_NAME="${{ inputs.IMAGE_NAME }}"
          IMAGE_REBUILD_TIME_LIMIT=${{ inputs.IMAGE_REBUILD_TIME_LIMIT }}

          # Query Artifactory for the image metadata
          RESPONSE=$(curl -s -u "${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }}" \
            -X GET "${ARTIFACTORY_URL}/artifactory/api/storage/${IMAGE_NAME}")

          # Check if the image exists
          if echo "$RESPONSE" | grep -q '"errors"'; then
            echo "Image not found in Artifactory. Proceeding with build."
            echo "SKIP_BUILD=NO" >> $GITHUB_ENV
          else
            # Extract the last modified timestamp
            LAST_MODIFIED=$(echo "$RESPONSE" | jq -r '.lastModified')
            echo "Image found in Artifactory. Last modified: $LAST_MODIFIED"

            # Convert the last modified timestamp to seconds since epoch
            LAST_MODIFIED_EPOCH=$(date -d "$LAST_MODIFIED" +%s)
            CURRENT_TIMESTAMP=$(date +%s)

            # Calculate the time difference
            TIME_DIFF=$((CURRENT_TIMESTAMP - LAST_MODIFIED_EPOCH))

            # Determine whether to skip the build
            if [ "$TIME_DIFF" -lt "$IMAGE_REBUILD_TIME_LIMIT" ]; then
              echo "Image was recently built. Skipping build."
              echo "SKIP_BUILD=YES" >> $GITHUB_ENV
            else
              echo "Image is outdated. Proceeding with build."
              echo "SKIP_BUILD=NO" >> $GITHUB_ENV
            fi
          fi

      - name: 🛠️ Pull latest DB base image then push to Artifactory
        if: env.SKIP_BUILD == 'NO'
        run: |
          docker pull ${{ env.IMAGE_NAME }}
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.ARTIFACTORY_URL }}/${{ env.IMAGE_NAME }}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{ env.IMAGE_NAME }}
