# Static Deploy On Openshift
# Builds and Deploys merged PR's to persistent pods/services/routes/etc in the OpenShift Dev environment.
name: Deploy on JFrog Artifactory

on:
  push:
    branches:
      - main
      - dev
      - test
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      -
        name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      -
        name: Login to JFrog 🐸
        uses: docker/login-action@v1
        with:
          registry: <your artifactory>.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_KEY }}
      -
        name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aro.jfrog.io/moodle/php:${{ github.ref_name }}






jobs:
  #Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Build ID: ${{ github.event.number }}
          echo Git Pull Request Ref: ${{ github.event.pull_request.head.sha }}
          echo OC CLI Version: $(oc version)
          echo Git Branch name: ${{ github.ref_name }}

  #Build the app

  build:
    name: Build APP
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name  == 'test' || github.ref_name  == 'prod'
    env:
      BUILD_ID: ${{ github.event.number }}
      BUILD_NAMESPACE: e66ac2-tools
      BRANCH: ${{ github.ref_name }}
      BUILD_TAG: ${{ github.ref_name }}
      APP: moodle
      DB_BACKUP_APP: db-backup
    steps:
      # Checkout the PR branch
      - name: Print env
        run: |
          echo BUILD ID: $BUILD_ID
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo BRANCH: $BRANCH
      - name: Checkout Target Branch
        uses: actions/checkout@v1
      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443

      # Build the app images
      - name: Build App images
        working-directory: "./openshift"
        run: |
          test -n "${BRANCH}"
          test -n "${BUILD_NAMESPACE}"
          echo "BUILIDING ${APP} with tag: ${BUILD_TAG}"
                oc -n ${BUILD_NAMESPACE} process -f docker-build.yml \
                -p TAG=${BUILD_TAG} \
                -p SOURCE_REPOSITORY_REF=${BRANCH} \
                -p BASE_IMAGE_NAME="ngnix" \
                -p BASE_IMAGE_TAG="latest" \
                -p SITE_URL="https://moodle-e66ac2-${BUILD_TAG}.apps.silver.devops.gov.bc.ca" \
                -p BASE_IMAGE_REPO="aro.jfrog.io/moodle/" \
                -p GITHUB_AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} \
                -p DB_HOST="mysql.mysql" \
                -p DB_PASSWORD="${{ secrets.DB_PASSWORD_ESCAPED }}" \
                -p DB_USER="moodle" \
                -p DB_NAME="moodle" \
                -p SOURCE_CONTEXT_DIR=. \
                -p NAME=${APP} | oc -n ${BUILD_NAMESPACE} apply -f -
          oc -n ${BUILD_NAMESPACE} start-build bc/${APP} --no-cache --wait

  # Deploy App images in Dev
  deployDev:
    name: Deploy APP to Dev environment
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    env:
      BUILD_ID: ${{ github.event.number }}
      CRON_PASSWORD: ${{ secrets.CRON_PASSWORD }}
      NAMESPACE: e66ac2-dev
      BUILD_NAMESPACE: e66ac2-tools
      BRANCH: ${{ github.ref_name }}
      APP: moodle
      APP_HOST: moodle-e66ac2-dev.apps.silver.devops.gov.bc.ca
      DB_HOST: mysql
      DB_HOST_2: mysql-read
      DB_BACKUP_APP: db-backup
      DB_NAME: moodle
    needs:
      - build
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v1

       # Log in to OpenShift.
       # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
       # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443

      - name: Deploy APP
        run: |
          test -n "${NAMESPACE}"
          test -n "${BUILD_NAMESPACE}"
          test -n "${BRANCH}"
          echo "Current namespace is ${NAMESPACE}"
          oc -n ${NAMESPACE} process -f openshift/web.json \
                -p APP_NAME=${APP} \
                -p SITE_URL=${APP_HOST} \
                -p DB_HOST=${DB_HOST} \
                -p DB_HOST_2=${DB_HOST_2} \
                -p MEMORY_LIMIT=1Gi \
                -p MEMORY_REQUEST=256Mi \
                -p CPU_LIMIT=2 \
                -p CPU_REQUEST=1 \
                -p PROJECT_NAMESPACE=${NAMESPACE} \
                -p VOLUME_SIZE=10Gi \
                -p BACKUP_VOLUME_SIZE=25Gi \
                -p HTTP_PORT=8080 \
                -p DB_PORT=3306 \
                -p APACHE_DOCUMENT_ROOT="/app/public" \
                -p SITE_NAME=Moodle \
                -p MOODLE_DATA_PATH="/app/moodledata" \
                -p MOODLE_DATA_MOUNT_PATH="/app" \
                -p BUILD_NAMESPACE="${BUILD_NAMESPACE}" \
                -p IMAGE_STREAM_TAG="moodle:${BRANCH}" \
                -p GITHUB_AUTH_TOKEN="${{ secrets.AUTH_TOKEN }}" \
                -p CRON_PASSWORD="${{ secrets.CRON_PASSWORD }}" | \
          oc -n ${NAMESPACE} apply -f -
          oc rollout latest dc/moodle -n ${NAMESPACE}
          # Check deployment rollout status every 10 seconds (max 10 minutes) until complete.
          ATTEMPTS=0
          ROLLOUT_STATUS_CMD="oc rollout status dc/moodle -n ${NAMESPACE}"
          until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 60 ]; do
            $ROLLOUT_STATUS_CMD
            ATTEMPTS=$((attempts + 1))
            sleep 10
          done
          oc project ${NAMESPACE}
          echo "Listing pods.."
          oc get pods|grep moodle
          for name in $podNames; do
            oc exec $podNames -- bash -c "
              cat <<- EOF > .env
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              SSL_PROXY=true
              SITE_URL=https://moodle-e66ac2-dev.apps.silver.devops.gov.bc.ca
              DB_HOST=mysql-0.mysql
              `EOF` "
          done
          export ROUTE="$(oc get route moodle -o jsonpath='{.spec.host}')"
          echo "${APP} is exposed at 'https://'${ROUTE}"
