name: Moodle

concurrency:
  group: moodle-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  APP: moodle
  USER: ${{ github.actor }}

on:
  workflow_call:
jobs:
  build-images:
    name: '🐸 Build to JFrog'
    runs-on: ubuntu-latest
    if: (github.ref_name == 'dev' || github.ref_name == 'test' || github.ref_name == 'prod')
    steps:
      # Checkout the PR branch
      - name: 📤 Checkout Target Branch
        uses: actions/checkout@v3

      # Login to Artifactory
      - name: 🔑 Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Setup Env Vars
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: example.env
          export-variables: true
          keys-case: upper

      - name: Setup Versions Env Vars
        id: dotenv_versions
        uses: falti/dotenv-action@v1
        with:
          path: example.versions.env
          export-variables: true
          keys-case: upper

      - name: 🛠️ Pull PHP base image
        run: |
          docker pull ${{ env.PHP_IMAGE }}
          docker tag ${{ env.PHP_IMAGE }} ${{ secrets.ARTIFACTORY_URL }}/${{ env.PHP_IMAGE }}
          docker push ${{ secrets.ARTIFACTORY_URL }}/${{ env.PHP_IMAGE }}

      - name: 🛠️ Build Moodle and Push to Artifactory
        run: docker buildx build --build-arg DOCKER_FROM_IMAGE=${{ secrets.ARTIFACTORY_URL }}/${{ env.PHP_IMAGE }} --tag ${{ secrets.ARTIFACTORY_URL }}/${{ env.MOODLE_DEPLOYMENT_NAME }}:${{ env.OPENSHIFT_DEPLOY_PROJECT }}-${{ github.ref_name }} --output=type=image,push=true --push -f ${{ env.MOODLE_DOCKER_FILE_PATH }} .

