name: Moodle

concurrency:
  group: moodle-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  APP: moodle
  USER: ${{ github.actor }}

on:
  workflow_call:
    inputs:
      MOODLE_BRANCH_VERSION:
        required: true
        type: string
      PSAELMSYNC_BRANCH_VERSION:
        required: true
        type: string
      HVP_BRANCH_VERSION:
        required: true
        type: string

jobs:
  build-images:
    name: '🐸 Build to JFrog'
    runs-on: ubuntu-22.04
    steps:
      # Checkout the PR branch
      - name: 📤 Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # Login to Artifactory
      - name: 🔑 Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Setup Env Vars
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: example.env
          export-variables: true
          keys-case: upper

      - name: 🐸 Buld to JFrog
        run: docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --build-arg MOODLE_BRANCH_VERSION=${{ env.MOODLE_BRANCH_VERSION }} --build-arg PSAELMSYNC_BRANCH_VERSION=${{ env.PSAELMSYNC_BRANCH_VERSION }} --build-arg HVP_BRANCH_VERSION=${{ env.HVP_BRANCH_VERSION }} --build-arg DOCKER_FROM_IMAGE=${{ secrets.ARTIFACTORY_URL }}/${{ env.PHP_DEPLOYMENT_NAME }}:${{ github.ref_name }} --tag ${{ secrets.ARTIFACTORY_URL }}/${{ env.MOODLE_DEPLOYMENT_NAME }}:${{ github.ref_name }} --output=type=image,push=true --push -f ${{ env.MOODLE_DOCKER_FILE_PATH }} .

