name: Moodle PHP CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - main
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "**"

defaults:
  run:
    shell: bash
    working-directory: ./builds/php/

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: build to check strictness
        id: build
        run: |
          docker build -t web .:
